name: Deploy VitePress Dalin DOCs Site

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build VitePress docs
        run: npm run docs:build

      - name: Deploy via rsync
        run: |
          sshpass -p "${{ secrets.SSH_USER_PASSWORD }}" rsync -av -e "ssh -o StrictHostKeyChecking=no -p 20007" ./docs/.vitepress/dist/ ${{ secrets.SSH_USER_NAME }}@${{ secrets.SSH_SERVER_NAME }}:/home/html/bobici.info/jirizejda.cz/public_html/dalin